name: Push To Person
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: testthedocs/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.MY_TEST_ACCESS_TOKEN }}
        BUILD_DIR: build # The folder the action should deploy.
        BUILD_SCRIPT: npm install && npm run-script build # The build script 
